# Generated by Django 5.1 on 2024-10-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('description1', models.TextField(blank=True, max_length=255, null=True)),
                ('description2', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag1', models.TextField(blank=True, max_length=55, null=True)),
                ('tag2', models.TextField(blank=True, max_length=55, null=True)),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('url_tab1', models.CharField(blank=True, max_length=55, null=True)),
                ('url_tab2', models.CharField(blank=True, max_length=55, null=True)),
                ('url_tab3', models.CharField(blank=True, max_length=55, null=True)),
                ('url_tab4', models.CharField(blank=True, max_length=55, null=True)),
                ('name_tab1', models.CharField(blank=True, max_length=55, null=True)),
                ('name_tab2', models.CharField(blank=True, max_length=55, null=True)),
                ('name_tab3', models.CharField(blank=True, max_length=55, null=True)),
                ('name_tab4', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'verbose_name': 'Entries',
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='EntriesBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='entries_blogs')),
            ],
            options={
                'verbose_name': 'Entries Blogs',
                'verbose_name_plural': 'Entries Blogs',
            },
        ),
        migrations.CreateModel(
            name='FeaturedBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('text', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='featured_blocks')),
            ],
            options={
                'verbose_name': 'Featured Blocks',
                'verbose_name_plural': 'Featured Blocks',
            },
        ),
        migrations.CreateModel(
            name='FeaturedPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description1', models.TextField(blank=True, max_length=255, null=True)),
                ('description2', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Featured Places',
                'verbose_name_plural': 'Featured Places',
            },
        ),
        migrations.CreateModel(
            name='ProjectsBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='projects_blocks')),
            ],
            options={
                'verbose_name': 'Projects Blocks',
                'verbose_name_plural': 'Projects Blocks',
            },
        ),
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('description1', models.TextField(blank=True, max_length=255, null=True)),
                ('description2', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Featured Places',
                'verbose_name_plural': 'Featured Places',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag1', models.TextField(blank=True, max_length=55, null=True)),
                ('tag2', models.TextField(blank=True, max_length=55, null=True)),
                ('tag3', models.TextField(blank=True, max_length=55, null=True)),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField(max_length=255)),
                ('link_url1', models.URLField(blank=True, null=True)),
                ('link_url2', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Videos',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
