# Generated by Django 5.1 on 2024-10-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_entries_entriesblogs_featuredblocks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recent',
            options={'verbose_name': 'Recent', 'verbose_name_plural': 'Recent'},
        ),
    ]
