# Generated by Django 5.1 on 2024-10-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_recent_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsblocks',
            name='link_url',
        ),
        migrations.AddField(
            model_name='projectsblocks',
            name='link_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
