# Generated by Django 5.1 on 2024-10-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_projectsblocks_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headertext',
            name='linck_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='headertext',
            name='link',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
