# Generated by Django 5.1 on 2024-10-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_headertext_linck_name_headertext_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headertext',
            old_name='linck_name',
            new_name='link_name',
        ),
    ]
