# Generated by Django 5.1 on 2024-10-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_mainblock_headertext_class_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainblock',
            options={'verbose_name': 'Main Block', 'verbose_name_plural': 'Main Blocks'},
        ),
    ]
