# Generated by Django 5.1 on 2024-10-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_mainblock_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntriesBlogs1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='entries_blogs1')),
            ],
            options={
                'verbose_name': 'Entries Blogs1',
                'verbose_name_plural': 'Entries Blogs1',
            },
        ),
        migrations.CreateModel(
            name='EntriesBlogs2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='entries_blogs2')),
            ],
            options={
                'verbose_name': 'Entries Blogs2',
                'verbose_name_plural': 'Entries Blogs2',
            },
        ),
        migrations.CreateModel(
            name='EntriesBlogs3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='entries_blogs3')),
            ],
            options={
                'verbose_name': 'Entries Blogs3',
                'verbose_name_plural': 'Entries Blogs3',
            },
        ),
        migrations.CreateModel(
            name='EntriesBlogs4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='entries_blogs4')),
            ],
            options={
                'verbose_name': 'Entries Blogs4',
                'verbose_name_plural': 'Entries Blogs4',
            },
        ),
        migrations.DeleteModel(
            name='EntriesBlogs',
        ),
    ]
